# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836c7d63333ac2de335e136fb68d9b30c4d62a9578a353fb445fb695b3a69321b69e682a56a64238d0f9845ede4dbe9a13c7ed0b797a46dc4433f51caad64662

test:
  secret_key_base: f9438d7e6401350230dc32f0d8a0a11b518b81a0a8680b148f4eec344733e587f2c49c5b4976e1c14830d01375dea42627b14be50082370c1a164ee74e4a4b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
